### ISSUE TITLE
IntelliJ shows decompiled .class file instead of source code

### ISSUE THREAD

**Issue by ddanelynn** [nus-cs2103-AY2021S2/forum#150] opened 2021-02-17 03:58 UTC
### May I know what I can do to display the code for the class?

<img width="469" alt="Screenshot 2021-02-17 at 11 57 04 AM" src="https://user-images.githubusercontent.com/66818697/108154060-41f9ab80-7117-11eb-9e19-ada811c1f6a8.png">
<img width="588" alt="Screenshot 2021-02-17 at 11 57 44 AM" src="https://user-images.githubusercontent.com/66818697/108154132-5f2e7a00-7117-11eb-8242-af6c6f3185eb.png">

**Comment by damithc** [comment] 2021-02-17 04:27
> After I clone tp and open the project in Intellij, the command.java file cannot be opened

How exactly did you open the project in Intellij?
Also, post a screenshot of the full IDE (to see exactly which folder you are expanding)

**Comment by ddanelynn** [comment] 2021-02-17 04:31
<img width="1162" alt="Screenshot 2021-02-17 at 12 29 41 PM" src="https://user-images.githubusercontent.com/66818697/108156535-d0702c00-711b-11eb-9a0c-83988ff384e2.png">

After the welcome page, I chose "open" to open the tp folder from my desktop.
<img width="801" alt="Screenshot 2021-02-17 at 12 30 24 PM" src="https://user-images.githubusercontent.com/66818697/108156588-eb42a080-711b-11eb-91b7-c34f83d3f872.png">

**Comment by damithc** [comment] 2021-02-17 04:45
hmm... just to be sure, you can try doing the whole thing again with a fresh clone.

**Comment by ddanelynn** [comment] 2021-02-17 04:48
I have already done that. The issue persisted. I have also redownloaded the Intellij application, did not fix the issue either.
I tried to delete the file and create a new one. But as long as the class name is "Command", it will automatically become a decompiled .class file.

**Comment by ddanelynn** [comment] 2021-02-17 04:49
I can open the file using VScode though.

**Comment by damithc** [comment] 2021-02-17 05:12
Didn't realize it was affecting just one class. Are you able to proceed with the project while we wait to see if someone else has encountered the same?

**Comment by ddanelynn** [comment] 2021-02-17 05:14
Yes, I am able to proceed but there are a lot red underlines indicating errors. But the program is able to run nonetheless. Thanks prof, will wait to see how it goes.

**Comment by damithc** [comment] 2021-02-17 05:18
> Yes, I am able to proceed but there are a lot red underlines indicating errors. 

This doesn't sound good. There seems to be something wrong with the project set up. Ensure you have followed all the steps in https://se-education.org/addressbook-level3/SettingUp.html

**Comment by tjtanjin** [comment] 2021-02-17 05:25
The issue [here](https://stackoverflow.com/questions/53382692/java-source-file-displaying-in-intellij-as-an-empty-decompiled-class-file) seems to be similar to the one you are facing, might want to give it a try :D

**Comment by ddanelynn** [comment] 2021-02-17 09:14
Solved by deleting the file name patterns for the java class file type

**Comment by damithc** [comment] 2021-02-17 10:01
Nice to hear that @Icelenaugust You can close this issue if the problem is solved already.
Thanks @tjtanjin for the help.

**Closed as completed** 2021-02-17 10:04 UTC
Labels: type-HelpRequest :sos:
