### ISSUE TITLE
java.lang.ClassNotFoundException: MainWindow occurs when Launcher.main() is run

### ISSUE THREAD

**Issue by nicoleang09** [nus-cs2103-AY2021S2/forum#89] opened 2021-02-01 07:34 UTC
After following the JavaFX tutorial part 4 and trying to run Launcher.main(), it results in a ClassNotFoundExecption in IntelliJ.
![Screenshot (75)](https://user-images.githubusercontent.com/60417365/106427364-32852c00-64a2-11eb-85eb-57a16d44efd9.png)

Here is the structure of my project.
<img src="https://user-images.githubusercontent.com/60417365/106427520-85f77a00-64a2-11eb-8e52-a6a0ceadf6f9.png"  width="300" />

**Comment by w2vgd** [comment] 2021-02-01 07:38
Have you changed your `MainWindow.fxml` to fit the controller name? As from your project structure, in your `MainWindow.fxml` file, I think that the `fx:controller` property of your AnchorPane should be changed to `fx:controller="duke.UI.MainWindow"`

**Comment by tjtanjin** [comment] 2021-02-01 07:39
Check if you imported `MainWindow` if you used it in a class from a different package :)

**Comment by nicoleang09** [comment] 2021-02-01 07:51
@w2vgd that helped, thanks!

**Comment by litone01** [comment] 2021-02-02 06:55
@w2vgd Thanks for the solution! It solves my issue as well!

**Comment by richardcom** [comment] 2021-02-06 07:48
Hi @nicoleang09 , just a gentle reminder to close the issue if the problem is solved. : )

**Closed as completed** 2021-02-06 07:51 UTC
Labels: type-HelpRequest :sos:
