### ISSUE TITLE
Unable to load resources in Fat Jar file

### ISSUE THREAD

**Issue by jingxueguo** [nus-cs2103-AY2021S2/forum#180] opened 2021-02-25 10:30 UTC
I was able to tun the application on IntelliJ by running `Launcher.main()`, and the `duke image, user image and MainWindow.fxml` loads normally. However, after creating the Fat Jar file using `./gradlew shadowJar`, I encountered `javafx.fxml.LoadException`
The full error message is attached below
![image](https://user-images.githubusercontent.com/37842102/109139794-dfe41a80-7796-11eb-8ef7-9a173b8c7127.png)

I am very confused as to why the jar file is unable to load the `MainWindow.fxml` and the images for Duke and User. `MainWindow.fxml` is stored under `src/main/resources/view`, and the images are stored under `src/main/resources/images` as per the iP guide.

The file paths used in Main.java and MainWindow.java are as followed
![image](https://user-images.githubusercontent.com/37842102/109140244-5b45cc00-7797-11eb-965e-c7bc0aba8205.png)
![image](https://user-images.githubusercontent.com/37842102/109140298-67ca2480-7797-11eb-8d9c-3eb2a83f09de.png)

Appreciate any help or advice! Thank you:>

**Comment by tjtanjin** [comment] 2021-02-25 10:36
Not sure what may have changed since your remote repository was last updated 2 days ago but a few points that might help: 

- In your `build.gradle` try changing `mainClassName` to `duke.Launcher` instead.
- Your images are named as `Duke.JPG` and `User.JPG`, try matching the casing as well.
- Use png files instead of jpg files.

Hopefully one of the above helps! :)

**Comment by w2vgd** [comment] 2021-02-25 10:41
Try using `.png` files instead as what @tjtanjin said and also maybe use the paths like this:
Either `"./images/User.png"` or `"images/User.png"`
 and similarly for other relative paths.

**Comment by jingxueguo** [comment] 2021-02-25 10:42
Hello! Thank you and changing the extension to png worked. Do you happen to know why must .png be used? I am not sure why this will affect the loading of MainWindow.fxml

**Comment by samuelfangjw** [comment] 2021-02-25 11:02
I don't believe the extension is the issue, I used .jpg in mine without any issues.

**Comment by samuelfangjw** [comment] 2021-02-25 11:14
I did a few quick tests with my own repo, I think it was because you named your pictures `Duke.JPG` and `User.JPG` and your image paths were `/images/User.jpg` and `/images/Duke.jpg`. I could also replicate your error when the extensions had different case. Changing the extension names to be consistent (either jpg or JPG) fixed it for me.

**Comment by damithc** [comment] 2021-02-26 02:53
thanks @samuelfangjw @tjtanjin @w2vgd for the help.
@jingxueguo you can close this issue if the problem is resolved.

**Closed as completed** 2021-02-26 07:13 UTC
Labels: type-HelpRequest :sos:
