### ISSUE TITLE
Questions regarding issue tracker

### ISSUE THREAD

**Issue by gycc7253** [nus-cs2103-AY2021S2/forum#1] opened 2021-01-16 03:48 UTC
Hi all,
May I ask how the issue page is supposed to look like after a few commits and tags pushed to origin..
What I have done are:
1. git add .
2. git commit -m "level x"
3. git push
4. git tag "level x"
5. git push origin --tags
But inside the page https://github.com/myusename/ip/issues url, it shows 'Welcome to Issues!' without my previous taggings and all.
Is it supposed to look like this?
![Screenshot (69)](https://user-images.githubusercontent.com/58676681/104796401-b7a8e980-57f0-11eb-8408-a6c8bd27f89a.png)

Thanks in advance!

**Comment by damithc** [comment] 2021-01-16 03:55
Yes @gycc7253 , that's fine. Issues page will be empty unless someone post an issue (it's like a discussion forum).
Your tags can be seen in https://github.com/gycc7253/ip/tags

**Comment by GabrielSimbingyang** [comment] 2021-01-16 14:37
Hi @gycc7253 ,

Previous CS2103T student here. 

Your commits and tags can be found at the **code** page of your repository. I have highlighted it in the following picture:

![image](https://user-images.githubusercontent.com/37536440/104814673-3cc0ec80-584b-11eb-897c-88c2f056b560.png)

The **issues** page that you are referring to behaves just like a forum, where different users can open post about the issues they are facing for others to respond/help.


Regards,
Gabriel Sim

**Comment by richardcom** [comment] 2021-01-16 14:46
Hi, the issues and tags are different in github.

The tag is a feature of git. On github, it can be found in the tags section in Code section of the github repo, as shown below:

![image](https://user-images.githubusercontent.com/65701775/104814916-5adb1c80-584c-11eb-9d4c-51e833f5264c.png)


While the issue is a feature of Github, an issue can be created using the Github Web interface as shown below:

![image](https://user-images.githubusercontent.com/65701775/104814953-94ac2300-584c-11eb-90fb-1acfe0f46a0d.png)

**Comment by Andrewzhang217** [comment] 2021-01-17 17:55
Hi, "Issues are a great way to keep track of tasks, enhancements, and bugs for your projects. They're kind of like email—except they can be shared and discussed with the rest of your team. Most software projects have a bug tracker of some kind. GitHub's tracker is called Issues, and has its own section in every repository."
Since no one reported a bug or found any issues in your code so it is totally fine that is empty.

**Comment by Diwu-Yi** [comment] 2021-01-18 01:59
Hi @gycc7253 , just a gentle reminder, if the clarifications are sufficient for you, now it is a good time to **close** this issue to keep the forum focused. Else, you can ask follow-up questions as comments :)

**Comment by danadi7** [comment] 2021-01-20 07:41
Hey @gycc7253, just another friendly reminder to **close** the issue if your question has been sufficiently answered. There should be a `Close Issue` button beside `Comment` on the reply box below.

Closing issues is not as urgent in a repo being used as a forum, such as this one. But in other projects and repos where the Issue Tracker is being used to track bugs, not closing an issue that has been resolved makes the issue tracker cluttered and more difficult for urgent bugs to be tracked as they might be pushed to later pages.

**Closed as completed** 2021-04-09 07:57 UTC
Labels: type-Question :thinking:
